[project]
name = "app"
version = "0.1.0"
description = "Lambda Function"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.13",
    "botocore>=1.40.13",
    "requests>=2.32.5",
]

[tool.uv.workspace]
members = ["functions"]
