# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class AssessmentProcessor:
        name: str
        type: str
    class AssessmentWebhookApi:
        type: str
        url: str
    class ProcessingFunction:
        name: str
        type: str
    class ProcessingQueue:
        type: str
        url: str

