services:
  app:
    container_name: ${ACTIVE_PROJECT}
    init: true
    environment:
      - $
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.12-bookworm
        ACTIVE_PROJECT: ${ACTIVE_PROJECT}
    volumes:
     - ../../${ACTIVE_PROJECT}:/workspaces/${ACTIVE_PROJECT}:cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: vscode

  al2023builder:
    image: public.ecr.aws/amazonlinux/amazonlinux:2023
    platform: linux/amd64
    container_name: ${ACTIVE_PROJECT}-al2023builder
    working_dir: /workspaces/${ACTIVE_PROJECT}
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - app
    volumes_from:
      - app